#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service with CSI LOGGING
#   Valid for Rocky 9 - FINAL CORRECTED VERSION
#
#---------------------------------------------------------------------

# STAGE 1: Build libcsi_logging library
FROM ran-base:latest AS csi-builder
RUN cd /tmp && \
    git clone https://github.com/turletti/oai-csi-logging.git && \
    cd oai-csi-logging && \
    mkdir -p build && cd build && \
    source /opt/rh/gcc-toolset-13/enable && \
    cmake .. && make && make install && ldconfig && \
    echo "✅ libcsi_logging.a built and installed to /usr/local/lib"

# STAGE 2: Build OAI with CSI integration
FROM ran-base:latest AS ran-build-csi
ARG E2AP_VERSION=E2AP_V3
ARG KPM_VERSION=KPM_V3_00

# Copy libcsi_logging from stage 1
COPY --from=csi-builder /usr/local/lib/libcsi_logging.a /usr/local/lib/
COPY --from=csi-builder /usr/local/include/csi_logging_init.h /usr/local/include/
COPY --from=csi-builder /usr/local/include/csi_oai_wrapper.h /usr/local/include/
COPY --from=csi-builder /usr/local/include/csi_rb_logging_external.h /usr/local/include/

# Copy OAI source
RUN rm -Rf /oai-ran
WORKDIR /oai-ran
COPY . .

# Copy csi_integration.c to both required locations
RUN cp csi_integration.c openair1/PHY/NR_ESTIMATION/ && \
    cp csi_integration.c openair1/PHY/NR_UE_TRANSPORT/ && \
    echo "✅ csi_integration.c copied to NR_ESTIMATION and NR_UE_TRANSPORT"

# Apply CSI patches to OAI source
RUN export OAI_DIR=/oai-ran && \
    chmod +x patch_csi_rx.sh patch_srs_ul.sh && \
    bash patch_csi_rx.sh && \
    bash patch_srs_ul.sh && \
    bash patch_csi_init_main.sh &&
    echo "✅ CSI patches applied (csi_rx.c and nr_ul_channel_estimation.c)"

# Update CMakeLists.txt: add csi_integration.c to compilation
RUN bash apply_csi_cmake.sh && \
    awk '/\$\{OPENAIR1_DIR\}\/PHY\/NR_ESTIMATION\/nr_ul_channel_estimation\.c/ && !done_ul {print; print "  ${OPENAIR1_DIR}/PHY/NR_ESTIMATION/csi_integration.c"; done_ul=1; next} 1' CMakeLists.txt > CMakeLists.txt.tmp && mv CMakeLists.txt.tmp CMakeLists.txt && \
    awk '/\$\{OPENAIR1_DIR\}\/PHY\/NR_UE_TRANSPORT\/csi_rx\.c/ && !done_ue {print; print "  ${OPENAIR1_DIR}/PHY/NR_UE_TRANSPORT/csi_integration.c"; done_ue=1; next} 1' CMakeLists.txt > CMakeLists.txt.tmp && mv CMakeLists.txt.tmp CMakeLists.txt && \
    echo "✅ CMakeLists.txt updated: csi_integration.c added to both locations"

# Link csi_logging to nr-softmodem and nr-uesoftmodem
RUN awk '/target_link_libraries\(nr-softmodem PRIVATE/ {in_target=1} in_target && /-Wl,--end-group/ && !done_soft {print "  csi_logging"; done_soft=1} {print}' CMakeLists.txt > CMakeLists.txt.tmp && mv CMakeLists.txt.tmp CMakeLists.txt && \
    awk '/target_link_libraries\(nr-uesoftmodem PRIVATE/ {in_target=1} in_target && /-Wl,--end-group/ && !done_ue {print "  csi_logging"; done_ue=1} {print}' CMakeLists.txt > CMakeLists.txt.tmp && mv CMakeLists.txt.tmp CMakeLists.txt && \
    echo "✅ csi_logging linked to nr-softmodem and nr-uesoftmodem"

# Build OAI with CSI support
RUN dnf install -y dnf-plugins-core && \
    dnf config-manager --set-enabled crb && \
    dnf install -y gcc-toolset-13 gcc-toolset-13-gcc-c++ gcc-toolset-13-binutils && \
    /bin/sh oaienv && \
    cd cmake_targets && \
    mkdir -p log && \
    source /opt/rh/gcc-toolset-13/enable && \
    CXXFLAGS='-Werror=format -fstack-protector-strong' \
    CFLAGS='-Werror=format -fstack-protector-strong' \
    ./build_oai -c --ninja \
      --eNB --gNB --RU --UE --nrUE \
      --build-e2 --cmake-opt -DE2AP_VERSION=$E2AP_VERSION \
      --cmake-opt -DKPM_VERSION=$KPM_VERSION \
      --cmake-opt '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-z,noexecstack' \
      --cmake-opt '-DCMAKE_EXE_LINKER_FLAGS=-Wl,-z,noexecstack' \
      --build-lib 'telnetsrv enbscope uescope nrscope' \
      --build-tool-opt -k10 -w USRP -t Ethernet --noavx512 && \
    echo "✅ OAI build with CSI SUCCESSFUL"

# Build FlexRIC for SM Models
RUN mkdir -p openair2/E2AP/flexric/build && \
    cd openair2/E2AP/flexric/build && \
    source /opt/rh/gcc-toolset-13/enable && \
    cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DKPM_VERSION=$KPM_VERSION -DE2AP_VERSION=$E2AP_VERSION .. && \
    ninja && ninja install && \
    echo "✅ FlexRIC build SUCCESSFUL"
